### ISSUE TITLE
Enable support for spark-3.x in Spear  

### ISSUE THREAD

**Issue by anudeep-modak** [romans-weapon/spear-framework#11]
Modify necessary code for enabling support for spark 3.x in spear framework

**Comment by AnudeepKonaboina** [comment]
Support for spark 3.x is completed and the supported versions of the related services within docker  are shown below

| Service      | Version     |
| -----------  | ----------- |
| Spark        | 3.1.1       |
| Hadoop       | 3.2.0       |
| Hive         | 3.1.1       |

Maven Release - 3.1.1-1.0 / Scala Version-2.12

```
spark shell --packages "io.github.romans-weapon:spear-framework_2.12:3.1.1-1.0"
```
