### ISSUE TITLE
Does the framework allow scope for writing  to multiple targets

### ISSUE THREAD

**Issue by training-techie** [romans-weapon/spear-framework#8]
Hello @AnudeepKonaboina Sir,
I want to write data from oracle table to s3 directly and also to hive after processing the source data. Below is the diagrammatic representation of  what i am trying to do.

![image](https://user-images.githubusercontent.com/85495131/121123912-a3b66080-c841-11eb-9878-ad80df91cc6a.png)

But  this framework is not allowing me to do as in the above diagram. I am forced to write two connectors ,rather than finish it off in one connector. It would be helpful if you could provide even that feature as a part of the framework sir.
Otherwise kudos to your framework it worked fine for one of my other use case for writhing Salesforce data to hdfs.

**Comment by AnudeepKonaboina** [comment]
Hey @training-techie ,

Thanks for writing to me .
I am currently working on the same feature of enabling multitargets for this framework .Will release the same soon with a new version
++ @Kalyan-D for awareness

**Comment by AnudeepKonaboina** [comment]
@training-techie ,
The enhancement is finally completed and released .The latest maven version is v2.4-2.0
Use the below command with you spark shell and execute your use-case of writing and let me know if it is resolved.

1. spark-shell
`
spark-shell --packages "io.github.romans-weapon:spear-framework_2.11:2.4-2.0"
`
2. library:
`
libraryDependencies += "io.github.romans-weapon" %% "spear-framework" % "2.4-2.0"
`

**Comment by AnudeepKonaboina** [comment]
@training-techie ,

FYI, The connector design for oracle to s3 and hive should look like below:

```scala
import com.github.edge.roman.spear.SpearConnector
import org.apache.log4j.{Level, Logger}
import org.apache.spark.sql.SaveMode

spark.sparkContext.hadoopConfiguration.set("fs.s3a.access.key", "***")
spark.sparkContext.hadoopConfiguration.set("fs.s3a.secret.key", "***")

Logger.getLogger("com.github").setLevel(Level.INFO)
val oracleMultiTargetConnector = SpearConnector
  .createConnector("ora-multi-target")
  .source(sourceType = "relational", sourceFormat = "jdbc")
  .multiTarget
  .getConnector
oracleMultiTargetConnector.setVeboseLogging(true)

oracleMultiTargetConnector
  .source(sourceObject = "table", Map("driver" -> "oracle.jdbc.driver.OracleDriver", "user" -> "user", "password" -> "*****", "url" -> "jdbc:oracle:thin:host:1521:orcl"))
    .saveAs("oracle_data")
    .branch
    .targets(
      oracleMultiTargetConnector.targetFS(destinationFilePath = "s3a://bucket/ora_data", destFormat = "parquet", saveMode = SaveMode.Overwrite),
      oracleMultiTargetConnector
        .transformSql(
          """
            |<your_transformation_sql>
            |""".stripMargin)
        targetFS(destinationFilePath = "/tmp/ingest", destFormat = "parquet", saveAsTable = "ingest.ora_data", saveMode = SaveMode.Overwrite)
    )

```

Hope this will resolve your requirement!! ++ @Kalyan-D

**Comment by training-techie** [comment]
Thanks a lot @AnudeepKonaboina  sir,
This will solve my use-case for sure. You can go ahead and close it now.
Thanks once again for your support.
