### ISSUE TITLE
provision for GraphDB(neo4j /neptune etc.) as source and target

### ISSUE THREAD

**Issue by code-roster** [romans-weapon/spear-framework#9]
++ @AnudeepKonaboina / @Kalyan-D ,

Is  there a provision to read from Graph DB and write to Hadoop? If yes can you give an example of how the connector would look like?

**Comment by AnudeepKonaboina** [comment]
@code-roster ,

Thanks for writing to us. We don't have the provision to read and write to Graph DB's yet ,but on your ask ,we will try to implement it in the future and let you know once it is released .Marking your issue as an enhancement.

**Comment by code-roster** [comment]
Thank you for that. There's on more use case of mine where I want to move some SAS datasets and ftp datasets to HDFS and S3 .Could you please help me on that as well . I see your framework also supports writing from and to filesystems. Could you elaborate more on that please?

**Comment by AnudeepKonaboina** [comment]
Could you please open another issue for this ? @Kalyan-D will be working on that.

**Comment by AnudeepKonaboina** [comment]
@code-roster ,

Provision for reading and writing to Graph database is now completed. You can use the latest maven Release for using that feature.

Maven Release:
```
 libraryDependencies += "io.github.romans-weapon" %% "spear-framework" % "2.4-3.0"
 ```

Example connectors:
1. [GraphDB as source](https://romans-weapon.github.io/spear-framework/#neo4j-to-postgres-connector) 
2. [GraphDB as Target](https://romans-weapon.github.io/spear-framework/#target-graphdb)

Please let me know if this satisfies your requirements.

**Comment by code-roster** [comment]
Thanks,
This is more than enough .Thanks for your support!!!
